		<div>
			<h2>Création de ton propre héros</h2>
			<form action="create.php" method="POST">
				<label for="name">Nom</label>
				<input type="text" name="name" id="name">
				<label for="hp">Points de vie</label>
				<input type="text" name="hp" id="hp">
				<label for="armor">Armure</label>
				<input type="text" name="armor" id="armor">
				<label for="weapon">Arme</label>
     	        <select name="weapon" id="weapon">
     	        	<?php
     	        	   	foreach ($weaponsList as $weapon):?>
						<option value="<?=$weapon['id']?>"><?=$weapon['weaponName']?></option>
					<?php endforeach; ?>
       			</select>
				<label for="avatar">Ton apparence</label>
				<input type="text" name="avatar" id="avatar">

				<button type="submit" name="submit">Valider</button>
			</form>
		</div>