<h1>Bienvenue dans l'arène</h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt architecto vero illum repellendus unde omnis exercitationem quia tempora, obcaecati quae quas veritatis nisi temporibus molestias id, a dolore est dicta!
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam ipsam expedita quos hic repellat rerum illum voluptates deserunt explicabo incidunt aliquid, nam necessitatibus unde et ipsa placeat delectus quasi. Rerum!
	</p>